### ISSUE TITLE
Add support to AngularJS and BootStrap

### ISSUE THREAD

**Issue by michaelhidalgo** [RoblesT/pyttacker#1]
==Enhancement request==

Even Though at this time we should not worry about the look&feel, AngularJS provides an interesting approach to interact with HTTP , Ajax still works just fine, but it will be cool to add support to this web technologies. When it comes to BootStrap it helps a lot too.

**Comment by mario-robles** [comment]
Thank you for the feedback and suggestions, both are great options and will
be considered

For now the project have a pretty simple interface since I've been spending
more time on the core server but your suggestions will be considered for
sure

If you want to provide some help, feel free to join

Thanks again

Mario

El 12/05/2014, a las 06:47 p.m., Michael Hidalgo notifications@github.com
escribió:

==Enhancement request==

Even Though at this time we should not worry about the look&feel, AngularJS
provides an interesting approach to interact with HTTP , Ajax still works
just fine, but it will be cool to add support to this web technologies.
When it comes to BootStrap it helps a lot too.

—
Reply to this email directly or view it on
GitHubhttps://github.com/RoblesT/pyttacker/issues/1
.
